version: '3'
services:
    app:
      build:
        context: './docker-runtime'
        dockerfile: Dockerfile
        args:
          WWWUSER: '${WWWUSER}'
          WWWGROUP: '${WWWGROUP:-33}'
      image: sail-7.4/app
      ports:
        - '8000:80'
      environment:
        LARAVEL_SAIL: 1
      volumes:
        - '${PWD:-./}:/app'
      depends_on:
        - mysql
        - redis
    mysql:
      image: mariadb
      env_file: ".env"
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_DB_HOST: '${DB_HOST}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      ports:
        - '3306:3306'
      volumes:
        - 'sailmysql:/var/lib/mysql'
    redis:
      image: 'redis:alpine'
      ports:
        - '${FORWARD_REDIS_PORT:-6379}:6379'
      volumes:
        - 'sailredis:/data'
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
volumes:
  sailmysql:
    driver: local
  sailredis:
    driver: local
